version: '3.9'

services:
  shop-backend:
    build: .
    container_name: shop-backend
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DefaultConnection=Host=aws-0-ap-southeast-1.pooler.supabase.com;Port=5432;Database=postgres;Username=postgres.kvnccjsnmrlzuhvlggih;Password=gjdTTYkG50uBWoW0;Ssl Mode=Require;Trust Server Certificate=true;
